version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@discordjs/opus"
    versions:
    - 0.4.0
  - dependency-name: ytdl-core
    versions:
    - 4.4.5
  - dependency-name: soundcloud-downloader
    versions:
    - 0.2.4
